workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: CodeMagic Integration
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zura.app
      vars:
        BUNDLE_ID: "com.zura.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Configure Firebase automatically
        script: |
          # Install FlutterFire CLI
          dart pub global activate flutterfire_cli
          
          # Auto-configure Firebase (this properly integrates the plist)
          flutterfire configure \
            --project=reel-match-e7729 \
            --platforms=ios \
            --ios-bundle-id=com.zura.app \
            --yes
      
      - name: Get Flutter dependencies
        script: |
          echo "📦 Getting Flutter dependencies..."
          flutter clean
          flutter pub get

      - name: Install iOS dependencies
        script: |
          echo "🍎 Installing iOS dependencies..."
          cd ios && pod install
      
      - name: Build iOS app
        script: |
          echo "🏗️ Building iOS app..."
          flutter build ios --release
      
      - name: Build iOS IPA
        script: |
          echo "📦 Creating IPA..."
          xcode-project build-ipa \
            --workspace ios/$XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false