workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: CodeMagic Integration
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zura.app
      vars:
        BUNDLE_ID: "com.zura.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - firebase_secrets
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Firebase configuration
        script: |
          echo "🔥 Setting up Firebase configuration..."
          echo $IOS_FIREBASE_SECRET | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo $ANDROID_FIREBASE_SECRET | base64 --decode > android/app/google-services.json
          echo "✅ Firebase configuration complete"

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios && pod install
      
      - name: Build iOS app
        script: |
          flutter build ios --release
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/$XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false