// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIuI1xHzx87eGzOcISYccCohTmBzRgpI',
    appId: '1:173034299087:web:ffd8bdf186f77f625ee1ba',
    messagingSenderId: '173034299087',
    projectId: 'reel-match-e7729',
    authDomain: 'reel-match-e7729.firebaseapp.com',
    storageBucket: 'reel-match-e7729.firebasestorage.app',
    measurementId: 'G-T6CCBYL91Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5YWzZGS_F-XGzNpZgEJXN7LId5mEmOs',
    appId: '1:173034299087:android:c7078ca974a06fd75ee1ba',
    messagingSenderId: '173034299087',
    projectId: 'reel-match-e7729',
    storageBucket: 'reel-match-e7729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyslqduejJ35SuAO7TEP4fJ40CQXdunkU',
    appId: '1:173034299087:ios:1dd69486e75fdd475ee1ba',
    messagingSenderId: '173034299087',
    projectId: 'reel-match-e7729',
    storageBucket: 'reel-match-e7729.firebasestorage.app',
    androidClientId: '173034299087-e19et72342kquoliq32200nmdb2207hk.apps.googleusercontent.com',
    iosClientId: '173034299087-ldk8k2rhifd6sdbvm0ac8kgsej9h4uq2.apps.googleusercontent.com',
    iosBundleId: 'com.zura.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyslqduejJ35SuAO7TEP4fJ40CQXdunkU',
    appId: '1:173034299087:ios:54a0a430043009795ee1ba',
    messagingSenderId: '173034299087',
    projectId: 'reel-match-e7729',
    storageBucket: 'reel-match-e7729.firebasestorage.app',
    androidClientId: '173034299087-e19et72342kquoliq32200nmdb2207hk.apps.googleusercontent.com',
    iosClientId: '173034299087-vcto11cals7j37psderonrg8bm07k99m.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieMatcherClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcIuI1xHzx87eGzOcISYccCohTmBzRgpI',
    appId: '1:173034299087:web:8367595e878f81f45ee1ba',
    messagingSenderId: '173034299087',
    projectId: 'reel-match-e7729',
    authDomain: 'reel-match-e7729.firebaseapp.com',
    storageBucket: 'reel-match-e7729.firebasestorage.app',
    measurementId: 'G-0H1ZCQWDN5',
  );
}
