const Set<String> moodboardBlacklist = {
  'based on comic',
  'duringcreditsstinger',
  'aftercreditsstinger',
  'un film minecraft',
  'una película de minecraft',
  'фильм',
  'short film',
  'tv movie',
  'featurette',
  'documentary short',
  'imax',
  'independent film',
  'screenlife',
  'anime',
  'cartoon',
  'mockumentary',
  'psychological drama',
  'docudrama',
  'musical number',
  'holiday special',
  'spin-off',
  'prequel',
  'sequel',
  'stand-alone sequel',
  'series reboot',
  '3d',
  '4dx',
  'hd',
  'remake',
  'retelling',
  'voice-over narration',
  'narration',
};
